[package]
name = "ruverta"
version = "0.1.0"
edition = "2021"
authors = ["kanade-k-1228"]
description = "Rust to Verilog: Very Simple Verilog Builder"
license = "MIT OR Apache-2.0"

[dependencies]

[features]
default = []
unstable = []
